const styles: { [key: string]: React.CSSProperties } = {
  body: {
    margin: 0,
    fontFamily: 'Segoe UI, Tahoma, Geneva, Verdana, sans-serif',
    background: 'linear-gradient(to right, #f5f7fa, #c3cfe2)',
    color: '#2c3e50',
    display: 'flex', 
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
    height: '100vh',
    width: '100vw',
    overflow: 'hidden',
  },
  dashboardContainer: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: '100vh',
    width: '100vw',
    textAlign: 'center',
    background: 'linear-gradient(to right,rgb(72, 139, 240), #c3cfe2)',
    padding: '0 2rem',
    boxSizing: 'border-box',
    overflow: 'hidden',
  },
  dashboardHeader: {
    background: 'linear-gradient(to right, #2c3e50, #4ca1af)',
    color: '#ecf0f1',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '1.5rem 2rem',
    boxShadow: '0 4px 10px rgba(0, 0, 0, 0.2)',
    zIndex: 10,
    width: '100%',
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    borderBottom: '2px solid #bdc3c7',
    backdropFilter: 'blur(10px)',
    borderRadius: '1px 1px 0px 0px',
    boxSizing: 'border-box',
    fontSize: '1.2rem',
    fontWeight: 600,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    textShadow: '0 1px 3px rgba(0, 0, 0, 0.2)',
    transition: 'background 0.3s ease, box-shadow 0.3s ease',
  },
  backButton: {
    backgroundColor: '#3498db',
    color: '#fff',
    border: 'none',
    padding: '0.6rem 1.2rem',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '1rem',
    boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
    transition: 'background-color 0.3s ease',
  },
  backButtonHover: {
    backgroundColor: '#2980b9',
  },
  dashboardTitle: {
    margin: 0,
    fontSize: '2.2rem',
    fontWeight: 700,
  },
  welcomeMessage: {
    fontSize: '1.1rem',
    fontWeight: 500,
  },
  dashboardMain: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: '2rem',
    padding: '3rem',
    flexGrow: 1,
    background: 'radial-gradient(circle at top left, #ffffff, #dfe9f3)',
    width: '93vw',
    height: '75vh',    

  },
  dashboardCard: {
    background: 'linear-gradient(135deg, #ffffff, #f1f2f6)',
    border: '2px solid #bdc3c7',
    borderRadius: '16px',
    padding: '2rem',
    textAlign: 'center',
    fontSize: '1.3rem',
    fontWeight: 600,
    color: '#2c3e50',
    boxShadow: '0 6px 16px rgba(0, 0, 0, 0.1)',
    transition: 'transform 0.3s ease, box-shadow 0.3s ease, color 0.3s ease, border-color 0.3s ease, background 0.3s ease',
    cursor: 'pointer',
    backdropFilter: 'blur(5px)',
    width: '200px',
    height: '200px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  dashboardCardHover: {
    transform: 'translateY(-6px) scale(1.05)',
    boxShadow: '0 12px 30px rgba(0, 0, 0, 0.2)',
    borderColor: '#3498db',
    color: '#3498db',
    background: 'linear-gradient(135deg, #ecf0f1, #d0d3d4)',
  },
  dashboardCardActive: {
    transform: 'scale(0.97)',
    boxShadow: 'inset 0 4px 10px rgba(0, 0, 0, 0.1)',
    borderColor: '#2980b9',
    background: 'linear-gradient(135deg, #d6eaf8, #aed6f1)',
  },
};

export default styles;