// entityPageStyles.ts

export const styles = {
  // Existing styles...
  container: {
    maxWidth: 1200,
    margin: '2rem auto',
    padding: '1rem',
  },
  headerContainer: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '1.5rem',
  },
  pageTitle: {
    color: '#e0e7ef',
    fontWeight: 700,
    fontSize: '2rem',
    letterSpacing: '0.02em',
  },
  addButton: {
    background: 'linear-gradient(90deg, #38bdf8 0%, #6366f1 100%)',
    color: '#fff',
    border: 'none',
    borderRadius: '0.75rem',
    padding: '0.75rem 1.5rem',
    fontWeight: 700,
    fontSize: '1rem',
    cursor: 'pointer',
    boxShadow: '0 2px 8px rgba(0,0,0,0.08)',
    transition: 'all 0.2s ease',
  },
  
  // New search-related styles
  searchContainer: {
    display: 'flex',
    marginBottom: '1.5rem',
    position: 'relative' as const,
    maxWidth: '100%',
  },
  searchInput: {
    width: '100%',
    padding: '0.75rem 1rem 0.75rem 2.75rem',
    borderRadius: '0.75rem',
    border: '1px solid #334155',
    background: 'rgba(51, 65, 85, 0.7)',
    color: '#f1f5f9',
    fontSize: '1rem',
    outline: 'none',
    transition: 'border 0.2s, box-shadow 0.2s',
  },
  searchIcon: {
    position: 'absolute' as const,
    left: '1rem',
    top: '50%',
    transform: 'translateY(-50%)',
    color: '#94a3b8',
    width: '1.25rem',
    height: '1.25rem',
  },
  clearButton: {
    position: 'absolute' as const,
    right: '1rem',
    top: '50%',
    transform: 'translateY(-50%)',
    background: 'transparent',
    border: 'none',
    color: '#94a3b8',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '0.25rem',
    borderRadius: '50%',
  },
  
  // Existing table styles...
  table: {
    width: '100%',
    borderCollapse: 'collapse' as const,
    borderRadius: '0.75rem',
    overflow: 'hidden',
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
  },
  tableHeader: {
    backgroundColor: 'rgba(51, 65, 85, 0.8)',
    color: '#cbd5e1',
    fontWeight: 600,
    fontSize: '1rem',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
  },
  tableRow: {
    backgroundColor: 'rgba(30, 41, 59, 0.85)',
    color: '#e0e7ef',
    transition: 'background 0.2s',
  },
  tableCell: {
    padding: '0.75rem 1rem',
    textAlign: 'left' as const,
    borderBottom: '1px solid rgba(51, 65, 85, 0.5)',
  },
  statusBadge: {
    padding: '0.25rem 0.75rem',
    borderRadius: '1rem',
    fontSize: '0.9rem',
    fontWeight: 600,
  },
  statusActive: {
    background: 'rgba(16, 185, 129, 0.15)',
    color: '#10b981',
  },
  statusInactive: {
    background: 'rgba(239, 68, 68, 0.15)',
    color: '#ef4444',
  },
  editButton: {
    background: 'rgba(51, 65, 85, 0.7)',
    color: '#cbd5e1',
    border: '1px solid #64748b',
    borderRadius: '0.75rem',
    padding: '0.5rem 1.25rem',
    fontWeight: 600,
    fontSize: '1rem',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  emptyMessage: {
    color: '#cbd5e1',
    textAlign: 'center' as const,
    padding: '3rem 0',
    fontSize: '1.1rem',
  },
  noResultsMessage: {
    color: '#cbd5e1',
    textAlign: 'center' as const,
    padding: '3rem 0',
    fontSize: '1.1rem',
    fontStyle: 'italic',
  },
  
  // Pagination styles
  paginationContainer: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: '1.5rem',
    padding: '0.5rem 0',
  },
  paginationInfo: {
    color: '#cbd5e1',
    fontSize: '0.95rem',
  },
  paginationControls: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  pageButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '2.5rem',
    height: '2.5rem',
    borderRadius: '0.5rem',
    border: '1px solid #334155',
    background: 'rgba(51, 65, 85, 0.7)',
    color: '#cbd5e1',
    fontSize: '0.95rem',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  pageButtonActive: {
    background: 'rgba(56, 189, 248, 0.2)',
    borderColor: '#38bdf8',
    color: '#38bdf8',
  },
  pageButtonDisabled: {
    opacity: 0.5,
    cursor: 'not-allowed',
  },
  pageSizeSelector: {
    padding: '0.5rem',
    borderRadius: '0.5rem',
    border: '1px solid #334155',
    background: 'rgba(51, 65, 85, 0.7)',
    color: '#cbd5e1',
    fontSize: '0.95rem',
    cursor: 'pointer',
    marginLeft: '0.5rem',
  },
  form: {
    maxWidth: 480,
    margin: "2rem auto",
    padding: "2rem",
    borderRadius: "1.5rem",
    background: "rgba(1, 1, 2, 0.85)", // glassy dark blue
    boxShadow: "0 8px 32px 0 rgba(31, 38, 135, 0.37)",
    backdropFilter: "blur(8px)",
    border: "1px solid rgba(255, 255, 255, 0.18)",
    display: "flex",
    flexDirection: "column" as const,
    gap: "1.5rem",
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '30px',
    paddingBottom: '20px',
    borderBottom: '1px solid rgba(0, 174, 255, 0.3)', // Brighter accent border
  },
  title: {
    fontSize: '2em',
    margin: 0,
    color: '#00d0ff', // Bright cyan
    textShadow: '0 0 8px rgba(0, 208, 255, 0.7), 0 0 12px rgba(0, 208, 255, 0.5)',
  },
  label: {
    fontWeight: 600,
    color: "#e0e7ef",
    marginBottom: "0.5rem",
    letterSpacing: "0.03em",
    fontSize: "1rem",
    display: "block",
  },
  input: {
    width: "100%",
    padding: "0.75rem 1rem",
    borderRadius: "0.75rem",
    border: "1px solid #334155",
    background: "rgba(51, 65, 85, 0.7)",
    color: "#f1f5f9",
    fontSize: "1rem",
    outline: "none",
    transition: "border 0.2s, box-shadow 0.2s",
    marginBottom: "0.5rem",
    "&:focus": {
      borderColor: "#38bdf8",
      boxShadow: "0 0 0 2px rgba(56, 189, 248, 0.3)",
    },
  },
  select: {
    width: "100%",
    padding: "0.75rem 1rem",
    borderRadius: "0.75rem",
    border: "1px solid #334155",
    background: "rgba(51, 65, 85, 0.7)",
    color: "#f1f5f9",
    fontSize: "1rem",
    outline: "none",
    transition: "border 0.2s, box-shadow 0.2s",
    marginBottom: "0.5rem",
    appearance: "none",
    backgroundImage: "url('data:image/svg+xml;utf8,<svg fill=\"%23f1f5f9\" height=\"24\" viewBox=\"0 0 24 24\" width=\"24\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M7 10l5 5 5-5z\"/></svg>')",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "right 0.75rem center",
    "&:focus": {
      borderColor: "#38bdf8",
      boxShadow: "0 0 0 2px rgba(56, 189, 248, 0.3)",
    },
  },
  textarea: {
    width: "100%",
    padding: "0.75rem 1rem",
    borderRadius: "0.75rem",
    border: "1px solid #334155",
    background: "rgba(51, 65, 85, 0.7)",
    color: "#f1f5f9",
    fontSize: "1rem",
    outline: "none",
    transition: "border 0.2s, box-shadow 0.2s",
    marginBottom: "0.5rem",
    minHeight: "120px",
    resize: "vertical" as const,
    "&:focus": {
      borderColor: "#38bdf8",
      boxShadow: "0 0 0 2px rgba(56, 189, 248, 0.3)",
    },
  },
  fieldGroup: {
    marginBottom: "1.5rem",
  },
  checkboxContainer: {
    marginBottom: "1rem",
  },
  checkboxLabel: {
    display: "flex",
    alignItems: "center",
    cursor: "pointer",
    userSelect: "none" as const,
  },
  checkbox: {
    position: "absolute" as const,
    opacity: 0,
    cursor: "pointer",
    height: 0,
    width: 0,
  },
  checkboxCustom: {
    position: "relative" as const,
    height: "1.5rem",
    width: "1.5rem",
    background: "rgba(51, 65, 85, 0.7)",
    borderRadius: "0.375rem",
    border: "1px solid #334155",
    display: "inline-block",
    transition: "all 0.2s ease",
    "&:after": {
      content: '""',
      position: "absolute" as const,
      display: "none",
      left: "0.5rem",
      top: "0.25rem",
      width: "0.375rem",
      height: "0.75rem",
      border: "solid #38bdf8",
      borderWidth: "0 2px 2px 0",
      transform: "rotate(45deg)",
    },
  },
  checkboxText: {
    marginLeft: "2.5rem",
    color: "#e0e7ef",
    fontWeight: 500,
    fontSize: "1rem",
  },
  buttonContainer: {
    display: "flex",
    justifyContent: "flex-start",
    marginTop: "1.5rem",
    gap: "1rem",
  },
  button: {
    padding: "0.75rem 1.5rem",
    borderRadius: "0.75rem",
    fontWeight: 700,
    fontSize: "1rem",
    border: "none",
    cursor: "pointer",
    transition: "all 0.2s ease",
    boxShadow: "0 2px 8px rgba(0,0,0,0.08)",
    "&:disabled": {
      opacity: 0.6,
      cursor: "not-allowed",
    },
    "&:focus": {
      outline: "none",
      boxShadow: "0 0 0 3px rgba(56, 189, 248, 0.4)",
    },
  },
  createButton: {
    background: "linear-gradient(90deg, #38bdf8 0%, #6366f1 100%)",
    color: "#fff",
    "&:hover:not(:disabled)": {
      boxShadow: "0 4px 12px rgba(56, 189, 248, 0.3)",
      transform: "translateY(-1px)",
    },
    "&:active:not(:disabled)": {
      transform: "translateY(0)",
    },
  },
  cancelButton: {
    background: "rgba(51, 65, 85, 0.7)",
    color: "#cbd5e1",
    border: "1px solid #64748b",
    "&:hover:not(:disabled)": {
      background: "rgba(71, 85, 105, 0.8)",
    },
  },
  error: {
    color: "#f87171",
    background: "rgba(239, 68, 68, 0.1)",
    borderRadius: "0.5rem",
    padding: "0.75rem 1rem",
    marginTop: "1rem",
    fontWeight: 500,
    fontSize: "1rem",
  },
  success: {
    color: "#22d3ee",
    background: "rgba(34, 211, 238, 0.1)",
    borderRadius: "0.5rem",
    padding: "0.75rem 1rem",
    marginTop: "1rem",
    fontWeight: 500,
    fontSize: "1rem",
  },
  infoText: {
    color: "#94a3b8",
    fontSize: "0.875rem",
    marginTop: "0.25rem",
  },
  attributesSection: {
    marginTop: "1.5rem",
    padding: "1rem",
    background: "rgba(30, 41, 59, 0.5)",
    borderRadius: "0.75rem",
    border: "1px solid rgba(71, 85, 105, 0.5)",
  },
  attributeRow: {
    display: "flex",
    gap: "1rem",
    marginBottom: "1rem",
    alignItems: "flex-start",
  },
  attributeInput: {
    flex: 1,
  },
  removeButton: {
    background: "rgba(239, 68, 68, 0.2)",
    color: "#ef4444",
    border: "1px solid rgba(239, 68, 68, 0.3)",
    borderRadius: "0.5rem",
    width: "2.5rem",
    height: "2.5rem",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    transition: "all 0.2s ease",
    marginTop: "1.75rem",
    "&:hover": {
      background: "rgba(239, 68, 68, 0.3)",
    },
  },
  addButton: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    background: "rgba(56, 189, 248, 0.2)",
    color: "#38bdf8",
    border: "1px solid rgba(56, 189, 248, 0.3)",
    borderRadius: "0.75rem",
    padding: "0.5rem 1rem",
    cursor: "pointer",
    transition: "all 0.2s ease",
    fontWeight: 600,
    "&:hover": {
      background: "rgba(56, 189, 248, 0.3)",
    },
  },

};