// entityPageStyles.ts

export const styles = {
  // Existing styles...
  container: {
    maxWidth: 1200,
    margin: '2rem auto',
    padding: '1rem',
  },
  headerContainer: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '1.5rem',
  },
  pageTitle: {
    color: '#e0e7ef',
    fontWeight: 700,
    fontSize: '2rem',
    letterSpacing: '0.02em',
  },
  addButton: {
    background: 'linear-gradient(90deg, #38bdf8 0%, #6366f1 100%)',
    color: '#fff',
    border: 'none',
    borderRadius: '0.75rem',
    padding: '0.75rem 1.5rem',
    fontWeight: 700,
    fontSize: '1rem',
    cursor: 'pointer',
    boxShadow: '0 2px 8px rgba(0,0,0,0.08)',
    transition: 'all 0.2s ease',
  },
  
  // New search-related styles
  searchContainer: {
    display: 'flex',
    marginBottom: '1.5rem',
    position: 'relative' as const,
    maxWidth: '100%',
  },
  searchInput: {
    width: '100%',
    padding: '0.75rem 1rem 0.75rem 2.75rem',
    borderRadius: '0.75rem',
    border: '1px solid #334155',
    background: 'rgba(51, 65, 85, 0.7)',
    color: '#f1f5f9',
    fontSize: '1rem',
    outline: 'none',
    transition: 'border 0.2s, box-shadow 0.2s',
  },
  searchIcon: {
    position: 'absolute' as const,
    left: '1rem',
    top: '50%',
    transform: 'translateY(-50%)',
    color: '#94a3b8',
    width: '1.25rem',
    height: '1.25rem',
  },
  clearButton: {
    position: 'absolute' as const,
    right: '1rem',
    top: '50%',
    transform: 'translateY(-50%)',
    background: 'transparent',
    border: 'none',
    color: '#94a3b8',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '0.25rem',
    borderRadius: '50%',
  },
  
  // Existing table styles...
  table: {
    width: '100%',
    borderCollapse: 'collapse' as const,
    borderRadius: '0.75rem',
    overflow: 'hidden',
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
  },
  tableHeader: {
    backgroundColor: 'rgba(51, 65, 85, 0.8)',
    color: '#cbd5e1',
    fontWeight: 600,
    fontSize: '1rem',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
  },
  tableRow: {
    backgroundColor: 'rgba(30, 41, 59, 0.85)',
    color: '#e0e7ef',
    transition: 'background 0.2s',
  },
  tableCell: {
    padding: '0.75rem 1rem',
    textAlign: 'left' as const,
    borderBottom: '1px solid rgba(51, 65, 85, 0.5)',
  },
  statusBadge: {
    padding: '0.25rem 0.75rem',
    borderRadius: '1rem',
    fontSize: '0.9rem',
    fontWeight: 600,
  },
  statusActive: {
    background: 'rgba(16, 185, 129, 0.15)',
    color: '#10b981',
  },
  statusInactive: {
    background: 'rgba(239, 68, 68, 0.15)',
    color: '#ef4444',
  },
  editButton: {
    background: 'rgba(51, 65, 85, 0.7)',
    color: '#cbd5e1',
    border: '1px solid #64748b',
    borderRadius: '0.75rem',
    padding: '0.5rem 1.25rem',
    fontWeight: 600,
    fontSize: '1rem',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  emptyMessage: {
    color: '#cbd5e1',
    textAlign: 'center' as const,
    padding: '3rem 0',
    fontSize: '1.1rem',
  },
  noResultsMessage: {
    color: '#cbd5e1',
    textAlign: 'center' as const,
    padding: '3rem 0',
    fontSize: '1.1rem',
    fontStyle: 'italic',
  },
  
  // Pagination styles
  paginationContainer: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: '1.5rem',
    padding: '0.5rem 0',
  },
  paginationInfo: {
    color: '#cbd5e1',
    fontSize: '0.95rem',
  },
  paginationControls: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  pageButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '2.5rem',
    height: '2.5rem',
    borderRadius: '0.5rem',
    border: '1px solid #334155',
    background: 'rgba(51, 65, 85, 0.7)',
    color: '#cbd5e1',
    fontSize: '0.95rem',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  pageButtonActive: {
    background: 'rgba(56, 189, 248, 0.2)',
    borderColor: '#38bdf8',
    color: '#38bdf8',
  },
  pageButtonDisabled: {
    opacity: 0.5,
    cursor: 'not-allowed',
  },
  pageSizeSelector: {
    padding: '0.5rem',
    borderRadius: '0.5rem',
    border: '1px solid #334155',
    background: 'rgba(51, 65, 85, 0.7)',
    color: '#cbd5e1',
    fontSize: '0.95rem',
    cursor: 'pointer',
    marginLeft: '0.5rem',
  },

};