export const styles = {
    // Copied from entitiesStyles.ts - ensure you create this file with full styles
    container: {
      maxWidth: 1200,
      margin: '2rem auto',
      padding: '1rem',
    },
    headerContainer: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: '1.5rem',
    },
    pageTitle: {
      color: '#e0e7ef',
      fontWeight: 700,
      fontSize: '2rem',
      letterSpacing: '0.02em',
    },
    addButton: {
      background: 'linear-gradient(90deg, #10b981 0%, #38bdf8 100%)', // Adjusted color
      color: '#fff',
      border: 'none',
      borderRadius: '0.75rem',
      padding: '0.75rem 1.5rem',
      fontWeight: 700,
      fontSize: '1rem',
      cursor: 'pointer',
      boxShadow: '0 2px 8px rgba(0,0,0,0.08)',
      transition: 'all 0.2s ease',
    },
    searchContainer: {
      display: 'flex',
      marginBottom: '1.5rem',
      position: 'relative' as const,
      maxWidth: '100%',
    },
    searchInput: {
      width: '100%',
      padding: '0.75rem 1rem 0.75rem 2.75rem',
      borderRadius: '0.75rem',
      border: '1px solid #334155',
      background: 'rgba(51, 65, 85, 0.7)',
      color: '#f1f5f9',
      fontSize: '1rem',
      outline: 'none',
      transition: 'border 0.2s, box-shadow 0.2s',
    },
    searchIcon: {
      position: 'absolute' as const,
      left: '1rem',
      top: '50%',
      transform: 'translateY(-50%)',
      color: '#94a3b8',
      width: '1.25rem',
      height: '1.25rem',
    },
    clearButton: {
      position: 'absolute' as const,
      right: '1rem',
      top: '50%',
      transform: 'translateY(-50%)',
      background: 'transparent',
      border: 'none',
      color: '#94a3b8',
      cursor: 'pointer',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      padding: '0.25rem',
      borderRadius: '50%',
    },
    table: {
      width: '100%',
      borderCollapse: 'collapse' as const,
      borderRadius: '0.75rem',
      overflow: 'hidden',
      boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
    },
    tableHeader: {
      backgroundColor: 'rgba(51, 65, 85, 0.8)',
      color: '#cbd5e1',
      fontWeight: 600,
      fontSize: '0.9rem', // Adjusted for more columns
      textTransform: 'uppercase' as const,
      letterSpacing: '0.05em',
      padding: '0.75rem 0.5rem', // Adjusted padding
    },
    tableRow: {
      backgroundColor: 'rgba(30, 41, 59, 0.85)',
      color: '#e0e7ef',
      transition: 'background 0.2s',
    },
    tableCell: {
      padding: '0.75rem 0.5rem', // Adjusted padding
      textAlign: 'left' as const,
      borderBottom: '1px solid rgba(51, 65, 85, 0.5)',
      fontSize: '0.9rem', // Adjusted for more columns
    },
    statusBadge: {
      padding: '0.25rem 0.75rem',
      borderRadius: '1rem',
      fontSize: '0.8rem',
      fontWeight: 600,
      textTransform: 'capitalize',
    },
    status_active: { // Match status values
      background: 'rgba(16, 185, 129, 0.15)',
      color: '#10b981',
    },
    status_inactive: {
      background: 'rgba(239, 68, 68, 0.15)',
      color: '#ef4444',
    },
    status_pending_provisioning: {
      background: 'rgba(245, 158, 11, 0.15)',
      color: '#f59e0b',
    },
    status_porting: {
      background: 'rgba(59, 130, 246, 0.15)',
      color: '#3b82f6',
    },
    editButton: {
      background: 'rgba(51, 65, 85, 0.7)',
      color: '#cbd5e1',
      border: '1px solid #64748b',
      borderRadius: '0.75rem',
      padding: '0.5rem 1rem',
      fontWeight: 600,
      fontSize: '0.9rem',
      cursor: 'pointer',
      transition: 'all 0.2s ease',
    },
    emptyMessage: {
      color: '#cbd5e1',
      textAlign: 'center' as const,
      padding: '3rem 0',
      fontSize: '1.1rem',
    },
    noResultsMessage: {
      color: '#cbd5e1',
      textAlign: 'center' as const,
      padding: '3rem 0',
      fontSize: '1.1rem',
      fontStyle: 'italic',
    },
    paginationContainer: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: '1.5rem',
      padding: '0.5rem 0',
    },
    paginationInfo: {
      color: '#cbd5e1',
      fontSize: '0.95rem',
    },
    paginationControls: {
      display: 'flex',
      alignItems: 'center',
      gap: '0.5rem',
    },
    pageButton: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      width: '2.5rem',
      height: '2.5rem',
      borderRadius: '0.5rem',
      border: '1px solid #334155',
      background: 'rgba(51, 65, 85, 0.7)',
      color: '#cbd5e1',
      fontSize: '0.95rem',
      fontWeight: 600,
      cursor: 'pointer',
      transition: 'all 0.2s ease',
    },
    pageButtonActive: {
      background: 'rgba(56, 189, 248, 0.2)',
      borderColor: '#38bdf8',
      color: '#38bdf8',
    },
    pageButtonDisabled: {
      opacity: 0.5,
      cursor: 'not-allowed',
    },
    pageSizeSelector: {
      padding: '0.5rem',
      borderRadius: '0.5rem',
      border: '1px solid #334155',
      background: 'rgba(51, 65, 85, 0.7)',
      color: '#cbd5e1',
      fontSize: '0.95rem',
      cursor: 'pointer',
      marginLeft: '0.5rem',
    },
    // Form specific styles (subset from entitiesStyles)
    form: {
      maxWidth: '600px', // Wider form for more fields
      margin: "2rem auto",
      padding: "2rem",
      borderRadius: "1.5rem",
      background: "rgba(1, 1, 2, 0.85)",
      boxShadow: "0 8px 32px 0 rgba(31, 38, 135, 0.37)",
      backdropFilter: "blur(8px)",
      border: "1px solid rgba(255, 255, 255, 0.18)",
      display: "flex",
      flexDirection: "column" as const,
      gap: "1.2rem", // Adjusted gap
    },
    formRow: { // For putting fields side-by-side
      display: 'flex',
      gap: '1rem',
    },
    formFieldHalf: {
      flex: 1,
    },
    label: {
      fontWeight: 600,
      color: "#e0e7ef",
      marginBottom: "0.5rem",
      display: "block",
      fontSize: "0.9rem",
    },
    input: {
      width: "100%",
      padding: "0.75rem 1rem",
      borderRadius: "0.75rem",
      border: "1px solid #334155",
      background: "rgba(51, 65, 85, 0.7)",
      color: "#f1f5f9",
      fontSize: "1rem",
      outline: "none",
      boxSizing: 'border-box' as const,
      transition: "border 0.2s, box-shadow 0.2s",
    },
    select: {
      width: "100%",
      padding: "0.75rem 1rem",
      borderRadius: "0.75rem",
      border: "1px solid #334155",
      background: "rgba(51, 65, 85, 0.7)",
      color: "#f1f5f9",
      fontSize: "1rem",
      outline: "none",
      boxSizing: 'border-box' as const,
      appearance: "none" as const,
      backgroundImage: "url('data:image/svg+xml;utf8,<svg fill=\"%23f1f5f9\" height=\"24\" viewBox=\"0 0 24 24\" width=\"24\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M7 10l5 5 5-5z\"/></svg>')",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "right 0.75rem center",
    },
    textarea: {
      width: "100%",
      padding: "0.75rem 1rem",
      borderRadius: "0.75rem",
      border: "1px solid #334155",
      background: "rgba(51, 65, 85, 0.7)",
      color: "#f1f5f9",
      fontSize: "1rem",
      outline: "none",
      boxSizing: 'border-box' as const,
      minHeight: "100px",
      resize: "vertical" as const,
    },
    checkboxGroup: {
      display: 'flex',
      gap: '1rem',
      alignItems: 'center',
      flexWrap: 'wrap' as const,
      marginTop: '0.5rem',
    },
    checkboxLabel: {
      display: "flex",
      alignItems: "center",
      cursor: "pointer",
      userSelect: "none" as const,
      color: "#e0e7ef",
      fontSize: "0.9rem",
    },
    checkbox: {
      marginRight: '0.5rem',
      width: '1rem',
      height: '1rem',
    },
    buttonContainer: {
      display: "flex",
      justifyContent: "flex-start",
      marginTop: "1.5rem",
      gap: "1rem",
    },
    button: {
      padding: "0.75rem 1.5rem",
      borderRadius: "0.75rem",
      fontWeight: 700,
      fontSize: "1rem",
      border: "none",
      cursor: "pointer",
      transition: "all 0.2s ease",
    },
    submitButton: { // Renamed from createButton for generic use
      background: "linear-gradient(90deg, #10b981 0%, #38bdf8 100%)",
      color: "#fff",
    },
    cancelButton: {
      background: "rgba(51, 65, 85, 0.7)",
      color: "#cbd5e1",
      border: "1px solid #64748b",
    },
    error: {
      color: "#f87171",
      fontSize: "0.875rem",
      marginTop: "0.25rem",
    },
    loadingText: {
      color: '#e0e7ef',
      textAlign: 'center' as const,
    },
    loadingContainer: {
      padding: '2rem',
    },
    // Add any other styles from entitiesStyles.ts that are needed
    header: { // From EntityAdd
      fontSize: '1.8em',
      color: '#00d0ff',
      marginBottom: '1.5rem',
      paddingBottom: '0.5rem',
      borderBottom: '1px solid rgba(0, 174, 255, 0.3)',
      textAlign: 'center' as const,
    },
    formGroup: {}, // Placeholder if used by EntityForm
     // ... other styles from entitiesStyles.ts if needed
  };